# $FreeBSD$

PORTNAME=	dotnet-sdk
DISTVERSION=	3.0.100-preview1-009019
CATEGORIES=	devel

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.TXT

MAINTAINER=	mateus@mateus.tech
COMMENT=	.NET Core SDK

MASTER_SITES=	https://gsocfiles.blob.core.windows.net/dotnet/
DISTFILES=	dotnet-freebsd-3.0.100-preview1-009019-MANAGEDONLY.tar.gz

MAKE_JOBS_UNSAFE=	yes
SDK_VERSION=	2.2.0-preview1-26620-03

.include <bsd.port.mk>
