# $FreeBSD$

PORTNAME=	dotnet-sdk
DISTVERSION=	3.0.100-preview1-009019
CATEGORIES=	devel
MASTER_SITES=	https://gsocfiles.blob.core.windows.net/dotnet/:sdk
DISTFILES=	dotnet-sdk-freebsd-3.0.100-preview1-009019.tar.gz:sdk

MAINTAINER=	mateus@mateus.tech
COMMENT=	.NET Core SDK

LICENSE=	MIT

MAKE_JOBS_UNSAFE=	yes
SDK_VERSION=	2.2.0-preview1-26620-03

.include <bsd.port.mk>
